services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web
  db:
    image: postgres:15.2
    restart: always
    container_name: character_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: character_service
    build:
      context: .
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    links:
      - db
volumes:
  postgres_data:
  static_volume:
  media_volume:
