"""initial

Revision ID: 9d5fb445d3d0
Revises: 
Create Date: 2023-12-13 00:38:21.018255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5fb445d3d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   # ### commands auto generated by Alembic - please adjust! ###
   op.create_table('character',
   sa.Column('id', sa.String(36), nullable=False),
   sa.Column('name', sa.String(), nullable=True),
   sa.Column('class_name', sa.String(), nullable=True),
   sa.Column('level', sa.Integer(), nullable=True),
   sa.Column('experience', sa.Integer(), nullable=True),
   sa.Column('strength', sa.Integer(), nullable=True),
   sa.Column('agility', sa.Integer(), nullable=True),
   sa.Column('intelligence', sa.Integer(), nullable=True),
   sa.Column('luck', sa.Integer(), nullable=True),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
   op.create_table('equipment',
   sa.Column('id', sa.Integer(), nullable=False),
   sa.Column('name', sa.String(), nullable=True),
   sa.Column('strength_impact', sa.Integer(), nullable=True),
   sa.Column('dex_impact', sa.Integer(), nullable=True),
   sa.Column('intelligence_impact', sa.Integer(), nullable=True),
   sa.Column('luck_impact', sa.Integer(), nullable=True),
   sa.Column('character_id', sa.String(36), nullable=True),
   sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
   # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
